apiVersion: v1
kind: Service
metadata:
  name: golang-backend-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: golang-backend-service
  ports:
    - port: 80
      targetPort: 80
